# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'interactive_live.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_InteractiveLiveContainer(object):
    def setupUi(self, InteractiveLiveContainer):
        InteractiveLiveContainer.setObjectName("InteractiveLiveContainer")
        InteractiveLiveContainer.resize(1125, 2436)
        self.question_container = QtWidgets.QFrame(InteractiveLiveContainer)
        self.question_container.setGeometry(QtCore.QRect(0, 730, 1125, 800))
        self.question_container.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.question_container.setFrameShadow(QtWidgets.QFrame.Raised)
        self.question_container.setObjectName("question_container")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.question_container)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(-17, 1, 1141, 801))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.h_layout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.h_layout.setContentsMargins(0, 0, 0, 0)
        self.h_layout.setSpacing(0)
        self.h_layout.setObjectName("h_layout")

        self.retranslateUi(InteractiveLiveContainer)
        QtCore.QMetaObject.connectSlotsByName(InteractiveLiveContainer)

    def retranslateUi(self, InteractiveLiveContainer):
        _translate = QtCore.QCoreApplication.translate
        InteractiveLiveContainer.setWindowTitle(_translate("InteractiveLiveContainer", "Form"))
